### ISSUE TITLE
Proposal to upstream vaikas/sigstore-scaffolding to a new repo under sigstore.

### ISSUE THREAD

**Issue by vaikas** [sigstore/tac#5]
During the meeting today 2022-03-01 I requested a repo that I could then upstream [sigstore-scaffolding](https://github.com/vaikas/sigstore-scaffolding) into a new repo under sigstore (proposed name: sigstore/scaffolding). I'm totes not wedded to name, I'm notoriously bad at naming things :) @lukehinds mentioned that new repo requests should be brought up to the TAC, so here we are.

We (Chainguard) have been using these in our tests for awhile now and have added integration testing into a couple of projects as well. For example in [Tekton Chains](https://github.com/tektoncd/chains/blob/main/.github/workflows/kind-e2e.yaml).

Some benefits of having it in the sigstore repo are (but not limited to):
 * Reduce the bus factor
 * Have consistent repo practices with other sigstore components (branch protection, gates for limiting commits (tests pass, etc.))
 * Folks have found it easy to get started with Sigstore using these pieces, having it co-located would be nicer
 * Make the capabilities more easily discoverable, so folks that are utilizing sigstore can have a well maintained and operated source for doing their integration testing with.

**Comment by dlorenc** [comment]
SGTM!

**Comment by lukehinds** [comment]
I am not strongly viewed, my main observation was that we are at a count of 36 repositories now. If folks find it useful I have no objection though.

**Comment by dlorenc** [comment]
> I am not strongly viewed, my main observation was that we are at a count of 36 repositories now. If folks find it useful I have no objection though.

I think the work tracked here will help make the repos scalable: https://github.com/sigstore/community/issues/53 and I just opened https://github.com/sigstore/tac/issues/7 to help trim down some extras that aren't used.

**Comment by bobcallaway** [comment]
SGTM as well

**Comment by dlorenc** [comment]
Closing!
